### ISSUE TITLE
Action state not resetting when binding gets removed

### ISSUE THREAD

**Issue by Alloc86** [pbhogan/InControlSupport#30] opened 2017-06-12 14:17 UTC
Hi,

think I found a new rare bug. Lets say you have two actions, A1 and A2.
- A1 initially bound to LeftAlt (not tested with others, suppose it doesn't matter), A2 doesn't matter
- Listen for binding on A2
- Press LeftAlt
A1 seems to first get the state updated to true, as it detects LeftAlt being pressed. Directly afterwards the LeftAlt binding is removed from A1 as it gets assigned to A2. Now the state of A1 is still true, as the binding is no longer there and A1 doesn't update to false anymore.

Workaround on my end right now: When receiving a new binding on an action I search *all* actions in *all* actionsets if they currently have the binding, that is to be assigned. On all those that currently have the binding I call ClearInputState, forcing the state to be reset. Not perfect but works for now.

Would be nice if the state was automatically reset if an active binding is removed from an action :)

Regards,
Chris

**Comment by pbhogan** [comment] 2017-06-12 18:34
That makes sense. I should be able to make it reset when a binding is removed, or at least figure out why it isn't clearing. In theory if there is no source it should be false/zero on the next update tick.

**Comment by pbhogan** [comment] 2017-06-13 01:19
So, I'm having trouble reproducing an actual issue here. Are you reading input from the action the same frame as a binding has been pressed but not released yet? When I set up the scenario above, A1 immediately changes to zero once I let go LeftAlt even though it rebinds to A2.

What I'm thinking of implementing is preventing input to all actions while any other action is listening on a set. There will be a flag on `PlayerActionSet` to turn this off since it might break expected behavior for someone.

Thoughts?

**Comment by Alloc86** [comment] 2017-06-13 16:01
Hm, maybe it's something on our end. I will give more details on what exactly we do doing the rebinding later tonight :)

**Comment by Alloc86** [comment] 2017-06-15 00:15
Ok, one night later ;)

What we basically do for binding new keys:
1. We set all PlayerActionSets to Enabled=false
2. We call ListenForBinding on the PlayerAction
3. When OnBindingFound is called we reenable all PlayerActionSets that were enabled before

I don't think the Enabled=false during that time should matter though as the PlayerActionSet (PAS) that was giving us trouble here was disabled during the whole ListenForBinding thing anyway. I.e. we have a PAS that contains actions for normal character control (movement etc) and one for UI interaction. While we're rebinding we're in the UI so the normal PAS is disabled all the time, only the one for the UI is enabled. Both the action we're binding to and the action that was originally bound to the new key are in the disabled player control PAS though. Not sure if that has anything to do with the issue though, as that combination of actions is the one that easily lets us reproduce the issue whereas I can't think of any other combination atm.

**Comment by pbhogan** [comment] 2017-06-15 01:19
Hmm. The only way I could replicate the issue is make sure A1 has exactly one binding, and while that binding is being held down, trigger something to remove it from A1. I could make this happen while listening for a binding, so I had to force it to happen. When that happened the value wouldn't clear because it had no bindings to read a zero value from. I've got a fix for this in the next update. I think along with the other changes I'm making to prevent input on actions while the set is listening, it should hopefully address the issue you're having.

I'm going to close this issue but If it still happens after the next update, we can reopen it.

**Closed as completed by pbhogan** 2017-06-15 01:19 UTC
